import { Body, Controller, Get, HttpCode, Injectable, Module, Param, ParseUUIDPipe, Post, Req } from '@nestjs/common';
import type { Request } from 'express';
import { ComposeMockInput, composeMockSchema, libraryVisibilitySchema } from '@ielts/validation';
import { AuditService } from '../audit/audit.service';
import { AppError, conflict, notFound } from '../common/app-error';
import { AuthUser, CurrentUser, RequirePermission, clientMeta } from '../common/decorators';
import { ZodPipe } from '../common/zod.pipe';
import { QuestionBankService } from '../question-bank/question-bank.service';
import { selectCandidates } from '../question-bank/selection';
import { PrismaService } from '../prisma/prisma.service';
import { QuestionBankModule } from '../question-bank/question-bank.module';

type Actor = { userId: string; ip?: string; userAgent?: string };
const uuid = new ParseUUIDPipe();

/**
 * Builds a mock paper from approved, published bank content. The result is a DRAFT: a person reviews it and
 * publishes it through the usual assessment flow. Nothing is generated by AI, and nothing reaches a student
 * until it is published and marked visible in the library.
 */
@Injectable()
export class MockExamsService {
  constructor(private readonly prisma: PrismaService, private readonly bank: QuestionBankService, private readonly audit: AuditService) {}

  async compose(input: ComposeMockInput, actor: Actor) {
    const day = new Date().toISOString().slice(0, 10);
    const cands = await this.bank.candidates({
      skill: input.skill, topic: input.topic, difficulty: { min: input.difficultyMin, max: input.difficultyMax },
    }, true);
    const ids = selectCandidates(cands, { count: input.count, seed: `mock|${input.title}|${day}` });
    if (ids.length < input.count) {
      throw new AppError('VALIDATION_ERROR', 422, `Only ${cands.length} matching question(s) are published. Lower the count or publish more content.`, { count: 'Not enough published questions.' });
    }
    return this.prisma.$transaction(async (tx) => {
      const a = await tx.assessment.create({
        data: {
          type: 'MOCK', origin: 'BANK', title: input.title, skill: input.skill, passPercent: 0, showAnswers: false,
          timeLimitMin: input.durationMin, libraryVisible: false,
        },
      });
      const paper = await this.bank.buildPaper(tx, a.id, ids, false);
      await this.audit.record({ ...actor, action: 'ADMIN_COMPOSED_MOCK', entityType: 'Assessment', entityId: a.id, after: { skill: input.skill, count: paper.questionCount } }, tx);
      return { assessmentId: a.id, questionCount: paper.questionCount, draftVersionId: paper.versionId };
    });
  }

  async list() {
    const rows = await this.prisma.assessment.findMany({
      where: { type: 'MOCK', origin: 'BANK' }, orderBy: { createdAt: 'desc' }, take: 100,
      select: { id: true, title: true, skill: true, timeLimitMin: true, libraryVisible: true, versions: { select: { version: true, publishedAt: true }, orderBy: { version: 'desc' }, take: 1 } },
    });
    return rows.map((r) => ({ ...r, published: !!r.versions[0]?.publishedAt }));
  }

  /** Only a published mock can be shown in the library. Hiding it again never affects attempts already made. */
  async setLibraryVisible(id: string, visible: boolean, actor: Actor) {
    return this.prisma.$transaction(async (tx) => {
      const a = await tx.assessment.findUnique({ where: { id }, select: { id: true, type: true, libraryVisible: true, versions: { select: { publishedAt: true } } } });
      if (!a || a.type !== 'MOCK') throw notFound('Mock exam');
      if (visible && !a.versions.some((v) => v.publishedAt)) throw conflict('CONFLICT', 'Publish the mock before showing it in the library.');
      const after = await tx.assessment.update({ where: { id }, data: { libraryVisible: visible } });
      await this.audit.record({ ...actor, action: 'ADMIN_CHANGED_MOCK_LIBRARY', entityType: 'Assessment', entityId: id, before: { libraryVisible: a.libraryVisible }, after: { libraryVisible: visible } }, tx);
      return { id: after.id, libraryVisible: after.libraryVisible };
    });
  }
}

const actorOf = (u: AuthUser, req: Request): Actor => ({ userId: u.id, ...clientMeta(req) });

@Controller('admin/mock-exams')
export class MockExamsController {
  constructor(private readonly mocks: MockExamsService) {}

  @RequirePermission('assessment.manage') @Get()
  list() { return this.mocks.list(); }

  @RequirePermission('assessment.manage') @Post('compose')
  compose(@Body(new ZodPipe(composeMockSchema)) body: ComposeMockInput, @CurrentUser() u: AuthUser, @Req() req: Request) {
    return this.mocks.compose(body, actorOf(u, req));
  }

  @RequirePermission('assessment.manage') @HttpCode(200) @Post(':id/library')
  library(@Param('id', uuid) id: string, @Body(new ZodPipe(libraryVisibilitySchema)) body: { visible: boolean }, @CurrentUser() u: AuthUser, @Req() req: Request) {
    return this.mocks.setLibraryVisible(id, body.visible, actorOf(u, req));
  }
}

@Module({
  imports: [QuestionBankModule],
  controllers: [MockExamsController],
  providers: [MockExamsService],
  exports: [MockExamsService],
})
export class MockExamsModule {}
